name: CI Infrastructure Workflow

on: 
  pull_request:
    branches:
      - devel
      - prod
      - stage
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/${{ github.event.github.base_ref }}
    steps: 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials 2
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -var "environment=${{ github.event.github.base_ref }}"
        continue-on-error: true
    
      - name: Terraform Apply
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        id: apply
        run: terraform apply -var "environment=${{ github.event.pull_request.base.ref }}" -auto-approve
        continue-on-error: true